services:
  # Base de données PostgreSQL dédiée au projet Bitcoin
  postgres-bitcoin:
    image: postgres:15
    container_name: bitcoin-backtesting-db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"  # Port différent pour éviter les conflits
    volumes:
      - bitcoin-postgres-data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - bitcoin-network

  # API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: bitcoin-backtesting-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./api:/app
    depends_on:
      - postgres-bitcoin
    restart: unless-stopped
    networks:
      - bitcoin-network

  # Interface web
  frontend:
    image: nginx:alpine
    container_name: bitcoin-backtesting-frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - bitcoin-network

volumes:
  bitcoin-postgres-data:

networks:
  bitcoin-network:
    driver: bridge 